apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stressor
  namespace: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress
  template:
    metadata:
      labels:
        app: memory-stress
    spec:
      containers:
      - name: stress
        image: polinux/stress
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "200M", "--timeout", "300s"]
