apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-generator
  namespace: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-generator
  template:
    metadata:
      labels:
        app: workload-generator
    spec:
      containers:
      - name: generator
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            REQ_COUNT=$(($RANDOM % 41 + 10))
            echo "Sending $REQ_COUNT requests to frontend..."
            for j in $(seq 1 $REQ_COUNT); do
              wget -qO- http://frontend-svc.workload.svc.cluster.local > /dev/null &
            done
            sleep 15
          done