kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Control plane node
  - role: control-plane
    extraPortMappings:
      - containerPort: 6443
        hostPort: 6443
      - containerPort: 2379
        hostPort: 2379
      - containerPort: 10251
        hostPort: 10251
  
  # Worker nodes
  - role: worker
  - role: worker
  - role: worker