apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus-server
  ports:
    - port: 9090      # Port inside the cluster
      targetPort: 9090 # Port on the container
      nodePort: 30090  # Static port on your laptop/node