apiVersion: v1
kind: Namespace
metadata:
  name: workload
---
# --- BACKEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: workload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: api
        image: nginx:1.21
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: workload
spec:
  selector:
    app: backend
  ports:
  - port: 80
---
# --- REDIS CACHE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  namespace: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: workload
spec:
  selector:
    app: redis
  ports:
  - port: 6379
---
# --- FRONTEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: web
        image: nginx:1.21
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: workload
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 80
